version: "3"

services:
    web:
        container_name: ${PROJECT_NAME}_web
        build:
            context: ./conf
            args:
                PHP_VERSION: '7.3'
        ports:
            - "80:80"
        volumes:
            - ./www:/app:delegated
        links:
            - db:db

    db:
        container_name: ${PROJECT_NAME}_db
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - fix-name-volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${PROJECT_NAME}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
          - db

    mailcatcher:
        image: dockage/mailcatcher:0.7.1
        ports:
            - "1080:1080"
            - "1025:1025"
        links:
            - web

volumes:
  fix-name-volume:
        name: ${PROJECT_NAME}-data # Real ending name
        external: false