version: "3"

services:
    web:
        container_name: presta_web
        build: ./conf/php
        ports:
            - "80:80"
        volumes:
            - ./conf/apache2/sites-available:/etc/apache2/sites-available
            - ./www:/var/www/html:cached
        links:
            - db:db

    db:
        container_name: presta_db
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: prestashop_dev

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        depends_on:
          - db

    mailcatcher:
        image: dockage/mailcatcher:0.7.1
        ports:
            - "1080:1080"
            - "1025:1025"
        links:
            - web

volumes:
  mysql-data: